api/controllers/newarticles.controller.js, api/database_accessor/articles_accessor.js, api/routes/pages.route.js
Added apiPostArticle() method in NewArticlesController.
Also added postArticles() method within ArticlesAccessor class, which utilizes MongoDB method insertOne() to send article to the database.
Although not related to this issue, I edited the path for my previously created "themes" route in pages.routes.js so that is would utilize the backtick feature and give it a cleaner look.
=> #14-Post-Request-to-Database-for-Articles

api/app.js, api/database_accessor/users.accessor.js, api/db/connection.js, api/models/User.js, api/models/article.js, api/routes/pages.route.js
Changed the connection code so that the database connection would only be established upon request, and closed following the response's success. Closes #21.
=> Contained db connection

api/auth/authorization.js, api/controllers/routes.controller.js, api/routes/error.route.js, api/routes/pages.route.js
=> Authorization now works based off of account permission level.

api/controllers/articles.controller.js, api/database_accessor/articles.accessor.js, api/models/article.js, api/routes/articles.route.js, package-lock.json, package.json, views/article.ejs
Closes #12, closes #6
Implements a proper controller/accessor to return a specific article, and uses the returned JSON data to return a barebones view. Returned JSON follows the structure of `api/models/article.js`.
=> Implement Articles View

api/controllers/articles.controller.js, api/controllers/users.controller.js, api/routes/articles.route.js, api/routes/pages.route.js, package.json
Additional Error Handling improvements, mainly for finished article views and the sign up page.
=> Error handling pages

api/app.js, api/auth/authorization.js, api/auth/protected.routes.js, api/controllers/admin.controller.js, api/controllers/articles.controller.js, api/controllers/newarticles.controller.js, api/controllers/public.pages.controller.js, api/controllers/users.controller.js, api/database_accessor/articles.accessor.js, api/database_accessor/users.accessor.js, api/error/errors.js, api/routes/articles.route.js, api/routes/internal.pages.route.js, api/routes/public.pages.route.js
PermissionsSet renamed to ProtectedRoutes - a more appropriate name
Added comments explaining classes and methods.
Renamed main router file to public router.
Separated routes into public and internal routes.
Removed unecessary imports.
=> Code has been organized

.gitignore, api/controllers/articles.controller.js, api/routes/articles.route.js, views/article.ejs
Supports mixing up of body paragraphs and pull quotes sections.
In elementOrder, it must be defined as a string "body" or "pull" to denote the type of section
=> rudimentary article views created.

public/js/submitarticle.js, views/post_article.ejs
Effect: Fields are now updated only immediately before submission of the create-articles form.
Code explanation:
Only file edited is submitarticle.js
In the function at the top of the file which runs once when the form is loaded, a new event listener is added to the form submission button:
```
document.getElementById("submit").addEventListener("click", () => {
updateFormFields();
});
```
This means that the function updateFormFields() will run once the form is submitted.
Other than that, all other instances of updateFormFields() have been removed from this file, as there should be no need to update the fields one-by-one as they are filled out, especially when they can all be processed at once when the form is submitted.
Result:
Submitted fields:
Before ticket completion (note "body3" is …
=> Fixed updated fields

api/routes/public.pages.route.js, public/css/contact.css, public/html/contact.html, public/html/index.html
Add a skeleton contact page, it currently borrows some CSS from W3 and skeleton but otherwise it's set up. Addresses ticket #47 and is routed in the public.pages.route.js.
=> Add Contact Page #47

api/routes/public.pages.route.js, public/css/contact.css, public/html/contact.html, public/html/index.html
My previous PR #86 had commits from #82 so it was subsequently reverted, I'm adding back all the changes since it's not showing up in the main branch.
=> Re-add #47

api/database_accessor/articles.accessor.js
[comment]: <N/A> (Put N/A if a section does not apply.)
- Implemented method in db_accessor that allows user to search articles by keyword in their title
- Still needs to be tested, will be done after the database is seeded
- N/A
- N/A
- N/A
Closes #100
=> 100 search articles by title keyword db accessor method

api/controllers/newarticles.controller.js, api/database_accessor/articles.accessor.js, api/error/error.handler.js, api/error/errors.js, api/models/pending.article.js, public/js/submitarticle.js, setup/drop.js, setup/reseed.js, setup/seed/articles_seed.js, setup/seed/pending_articles_seed.js, views/post_article.ejs
`apiPostArticle` is the main method used to post articles to the database
First an error is thrown if there is a non-numericle entry for year.  Then the method check that there isn't already an article with the given title that exists.  If not, the article is posted to the database.
New methods `getArticleByTitle` and `getPendingArticleByTitle` have been implemented, both of which retrieve the article from the database with the given title.  These are used to confirm that there is not already an article from the database with the current title.
These files contain two new errors, `PostArticle.Year` and `PostArticle.Title`.  The former runs if an invalid entry is given for an article's year (non-numerical) and the latter run if an already existing article title is given for a new article. …
=> #78 process req.body data upon article submission post

api/models/article.js, api/models/helper.js, package-lock.json, package.json
Changed variable names and added a denied enumerated type
=> 96 article status

api/database_accessor/articles.accessor.js
- The sortArticles method follows the structure of previous methods and attempts to sort the articles from oldest to newest. It starts by defining parameters for the function and then sets a try-catch block to catch any errors during the execution of the code inside. It then opens up a connection and waits for it to be established. The if-else block checks the sorting order. If the order is ascending, then the sortOrder is set to 1, else it's set to -1. The constant skip is used for pagination and the constant articles find all the articles, sort them by the sortBy field in sortOrder, skip certain articles, and then limit the number of articles on a certain page to improve speed. Finally, the function just returns the sorted articles.
- …
=> 101 sort articles in order of oldest to newest db accessor method

api/database_accessor/articles.accessor.js
- Implemented the getArticlesByCategory function in the db articles accessors
- Needs testing
- N/A
- N/A
- N/A
Closes #98
=> #98 added getArticlesByCategory function

api/models/enums/account_status.js, api/models/enums/article_status.js, api/models/enums/design_status.js, api/models/enums/internal_comment_status.js, api/models/enums/photography_status.js, api/models/enums/writing_status.js
- created enumerated classes for each required status type
- error handling for incorrect strings in the verification method hasn't been implemented because there is no system yet.
- 
- N/A
- N/A
Closes #132 #133 #134 #135 #136 #137
=> 132-137 create all enums

.prettierrc.json, api/api_models/base_model.js, api/api_models/user.js, api/controllers/newarticles.controller.js, api/error/internal_errors.js
- Created the BaseModel API class that all other API Models will extend, with validation upon construction.
- Create the User API Models
- validate method on BaseModel can be cleaned up and more edge cases can be handled, but it works as intended.
-  None
- None
- N/A
Closes #146
Closes #147 
Closes #144
Closes #148
Closes #151
=> Api model class

api/database_accessor/articles.accessor.js
- Created GET methods for Article schema
- getArticleByTitle, getArticlesByAuthorID, getArticlesByEditorID, getArticlesByCategory, getArticlesByCreationDate, getArticlesByModifiedDate, getArticleBySlug, getArticleByIssueNumber, getArticlesByArticleStatus, getArticlesByWritingStatus, getArticlesByPhotographyStatus, getArticlesByDesignStatus, getArticle(articleID)
- removed old methods from file
- additional methods to add / what added methods should actually be removed if they are not that useful
- how to get articles based on an author's username?
- how to get articles by multiple categories?
- is ArticleCategory a thing? On the data definitions spread sheet I saw categories was a list of ArticleCategory but I couldn't find it
- does …
=> #149 add get methods to articles schema

api/database_accessor/articles.accessor.js, api/database_accessor/photo.accessor.js, api/database_accessor/users.accessor.js, api/error/internal_errors.js, api/models/article.js, api/models/enums/account_status.js, api/models/enums/accounts.js, api/models/enums/article_content.js, api/models/enums/article_status.js, api/models/enums/categories.js, api/models/enums/comment_status.js, api/models/enums/design_status.js, api/models/enums/photography_status.js, api/models/enums/writing_status.js
- Added todos on user and article accessor.
- Added listr and list and toString methods onto all enums.
- None
- None
- None
- N/A
Closes Nothing at all
=> Consistency changes

api/api_models/base_model.js, api/api_models/user.js
- Removed the need to define constructors on API models explicitly. Added default and override options for API Models
- None
- None
- None
- N/A
Closes Nothing at all
=> Api model redesign

api/models/api_models/article.js, api/models/db_models/article.js
- Created all API Article models
-  None
- None
- None
- N/A
Closes #152 
Closes #153 
Closes #154
Closes #156
=> Article api models

api/api_models/photo_tags.js, api/api_models/photos.js
=> 170 api models for photo and phototag. Check if this is right and I'll do the other one

app/controllers/userController.js, app/databaseAccessors/userAccessor.js, app/error/httpErrors.js, app/routes/userRoutes.js, tests/__tests__/apiTests/default.js, tests/__tests__/apiTests/userTest.js, tests/testData/tokenTestData.js, tests/testData/userTestData.js, tests/util.js
- Created the /user/login route
- Updated login method in `userController` for accurate error handling and outdated `getRegisteredUser` and outdated controller methods
- Replaced outdated instances of `getRegisteredByUsername` and `getUnregisteredByUsername` with newly created methods `getApprovedByUsername` and `getApprovedByUsername` in `userAccessor.js` which takes advantage of the enum status value
-  A successful login results in a response the creation of a cookie with lifespan of 1 hour, called "token" that carries a JWT encrypted token of the user's username and roles within NU Sci.  A 200 success response is sent along with a JSON message saying "test succesful"
- Added `tokenTestData` in `testData` which exports lists of …
=> Added login route and tests; added login tokens for testing

app/controllers/userController.js, app/routes/userRoutes.js, tests/__tests__/apiTests/userTest.js, tests/testData/userTestData.js
[comment]: Bulk of the ticket was already completed/implemented through existing db accessor and controller methods. The only changes I made on these implementations was on the controller method, and there was a comment left on why the change was made. Test cases are added in the userTest.js. 
- summarized in the comment .
- 
- added return statement to getPublicProfile in user controllers. This is to handle the case that the user is not found and returned as null/undefined, and ensures that the type error due to user.toObject() is not thrown after the 404 error is thrown. 
- n/a
- test valid username queries (2)
- test invalid username (1)
Closes #212
=> finished implementation and tests

app/auth/authorization.js, app/controllers/articleController.js, app/controllers/userController.js, app/databaseAccessors/articleAccessor.js, app/databaseAccessors/calendarAccessor.js, app/databaseAccessors/issueMapAccessor.js, app/databaseAccessors/photo.accessor.js, app/databaseAccessors/photoTagAccessor.js, app/databaseAccessors/userAccessor.js, app/db/connection.js, app/error/httpErrors.js, jest.config.cjs, tests/__tests__/api/article/postCommentCreate.js, tests/__tests__/api/user/postLogin.js, tests/__tests__/api/user/postSignup.js
[comment]: <> (Put a brief summary of your changes.)
- Fixed standard error handling in the accessor files, and made `Connection.open()` actually throw a database error connection. 
- Flattened user login, so that instead of 5 nested if-elses, if we encounter an error situation,  we just throw immediately. 
- It looks like a lot of changes, because its across the board, but its a relatively simple fix.
- I will release a new PR soon with a potential fix to error handling, to make it make more sense, and have it be a lot more streamlined and less verbose. This PR just conforms to the current error handling protocol.
[comment]: <> (Note any …
=> Some error handling fixes, and flattening of large if-elses

tests/__tests__/unit/enum/accountStatus.js, tests/__tests__/unit/enum/accounts.js, tests/__tests__/unit/enum/articleContent.js, tests/__tests__/unit/enum/articleStatus.js, tests/__tests__/unit/enum/category.js, tests/__tests__/unit/enum/commentStatus.js, tests/__tests__/unit/enum/designStatus.js, tests/__tests__/unit/enum/photographtStatus.js, tests/__tests__/unit/enum/writingStatus.js
[comment]: <> (Put a brief summary of your changes.)
- removed log
- 
- 
- 
[comment]: <> (Note any new endpoints, deleted endpoints, or updated endpoints.)
- 
- 
[comment]: <> (Note changes to any database schemas.)
- 
- 
[comment]: <> (Note any new or modified test cases.)
- 
- 
[comment]: <> (Put the ticket # this PR closes.)
Closes #
=> removed log

app/models/dbModels/issueMap.js
[comment]: <> (Put a brief summary of your changes.)
- Added the `unique: true` flag for issueMaps for Mongoose Schema
- 
- 
[comment]: <> (Note any new endpoints, deleted endpoints, or updated endpoints.)
- 
- 
[comment]: <> (Note changes to any database schemas.)
- issueNumbers for issueMaps must be unique.
[comment]: <> (Note any new or modified test cases.)
- 
- 
[comment]: <> (Put the ticket # this PR closes.)
Closes #262
=> 262 Made issueNumber unique per issue map in the database

app/models/enums/commentStatus.js, tests/__tests__/unit/enum/commentStatus.js
[comment]: <> I created the Reason enum and changed tests so that I can accommodate for the existence of this enum and made sure the methods that are available for comment status enums are working. 
- 
- 
- Um, is there anything else I should do for this or was the ticket just creating the enum. 
- 
[comment]: <> (Note any new endpoints, deleted endpoints, or updated endpoints.)
- 
- 
[comment]: <> (Note changes to any database schemas.)
- 
- 
[comment]: <> Created new tests to test for Reason enum.
- 
- 
[comment]: <> #250 
Closes #
=> Added a Reason enum and changed tests to accomadate for the enum

app/app.js, app/controllers/photoTagController.js, app/databaseAccessors/photoTagAccessor.js, app/error/errors.js, app/models/validationSchemas/photoTag.js, app/routes/photoTagRoutes.js, tests/__tests__/api/photoTag/getPhotoTag.js, tests/__tests__/api/photoTag/postCreatePhotoTag.js, tests/testData/photoTagTestData.js, tests/testData/userTestData.js
[comment]: <> (Put a brief summary of your changes.)
- Implemented the endpoint `/photo-tag/:tagName` where the provided `:tagName` is used to obtain a photoTag from the database
- Added relevant errors and tests 
- Because all photoTag routes already use "photoTag", the full url is `/photo-tag/photo-tag/:tagName` which feels redundant
[comment]: <> (Note any new endpoints, deleted endpoints, or updated endpoints.)
- Added endpoint `/phototag/name/:tagName` 
[comment]: <> (Note changes to any database schemas.)
- N/A
[comment]: <> (Note any new or modified test cases.)
- Added test data and tests in `photoTagTestData.js` and …
=> #198 endpoint get photo tag by tag name
